<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DayLicensesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run(){
        $data = [
            ["id"=>"1","name"=>"BackOffice Selindo (BOS)","serial"=>null,"purchase_date"=>null,"purchase_cost"=>null,"order_number"=>null,"seats"=>"1","notes"=>"Sistem informasi yang terintegrasi mulai dari Anggaran, permintaan belanja, penghitungan dan realisasi keuangan serta Presensi","user_id"=>null,"depreciation_id"=>null,"created_at"=>"08/31/2023 16:51:00","updated_at"=>null,"deleted_at"=>null,"license_name"=>null,"license_email"=>null,"depreciate"=>null,"supplier_id"=>null,"expiration_date"=>null,"purchase_order"=>null,"termination_date"=>null,"maintained"=>"0","reassignable"=>"1","company_id"=>"10","manufacturer_id"=>null,"category_id"=>"16","mulaiberlaku"=>null],
            ["id"=>"2","name"=>"Absensi (backoffice)","serial"=>null,"purchase_date"=>null,"purchase_cost"=>null,"order_number"=>null,"seats"=>"1","notes"=>"Aplikasi untuk kontrol kehadiran dan ketidakhadiran pegawai","user_id"=>null,"depreciation_id"=>null,"created_at"=>"09/01/2023 16:51:00","updated_at"=>null,"deleted_at"=>null,"license_name"=>null,"license_email"=>null,"depreciate"=>null,"supplier_id"=>null,"expiration_date"=>null,"purchase_order"=>null,"termination_date"=>null,"maintained"=>"0","reassignable"=>"1","company_id"=>"10","manufacturer_id"=>null,"category_id"=>"16","mulaiberlaku"=>null],
            ["id"=>"3","name"=>"Monev","serial"=>null,"purchase_date"=>null,"purchase_cost"=>null,"order_number"=>null,"seats"=>"1","notes"=>"Aplikasi untuk mengelola dokumen monev","user_id"=>null,"depreciation_id"=>null,"created_at"=>"09/02/2023 16:51:00","updated_at"=>null,"deleted_at"=>null,"license_name"=>null,"license_email"=>null,"depreciate"=>null,"supplier_id"=>null,"expiration_date"=>null,"purchase_order"=>null,"termination_date"=>null,"maintained"=>"0","reassignable"=>"1","company_id"=>"10","manufacturer_id"=>null,"category_id"=>"16","mulaiberlaku"=>null],
            ["id"=>"4","name"=>"Simpeg Online","serial"=>null,"purchase_date"=>null,"purchase_cost"=>null,"order_number"=>null,"seats"=>"1","notes"=>"SIMPEG-BPS merupakan aplikasi berbasis web untuk menunjang perekaman data administrasi pegawai.","user_id"=>null,"depreciation_id"=>null,"created_at"=>"09/03/2023 16:51:00","updated_at"=>null,"deleted_at"=>null,"license_name"=>null,"license_email"=>null,"depreciate"=>null,"supplier_id"=>null,"expiration_date"=>null,"purchase_order"=>null,"termination_date"=>null,"maintained"=>"0","reassignable"=>"1","company_id"=>"10","manufacturer_id"=>null,"category_id"=>"16","mulaiberlaku"=>null],
            ["id"=>"5","name"=>"Presensi BPS","serial"=>null,"purchase_date"=>null,"purchase_cost"=>null,"order_number"=>null,"seats"=>"1","notes"=>"Aplikasi presensi BPS untuk memantau kehadiran Pegawai. Membuat laporan data presensi menjadi lebih mudah cukup dengan smartphone. Memberikan hasil yang lebih akurat tanpa menggunakan fingerprint sehingga lebih hemat.","user_id"=>null,"depreciation_id"=>null,"created_at"=>"09/04/2023 16:51:00","updated_at"=>null,"deleted_at"=>null,"license_name"=>null,"license_email"=>null,"depreciate"=>null,"supplier_id"=>null,"expiration_date"=>null,"purchase_order"=>null,"termination_date"=>null,"maintained"=>"0","reassignable"=>"1","company_id"=>"10","manufacturer_id"=>null,"category_id"=>"16","mulaiberlaku"=>null],
            ["id"=>"6","name"=>"Baperjakat Online","serial"=>null,"purchase_date"=>null,"purchase_cost"=>null,"order_number"=>null,"seats"=>"1","notes"=>"Menampilkan daftar pegawai yang memenuhi syarat untuk diangkat menjadi Eselon I, II, III, atau IV. Menampilkan Nominasi Jabatan disusun berdasarkan DUK (pangkat, jabatan, masa kerja, latihan jabatan, pendidikan dan usia).","user_id"=>null,"depreciation_id"=>null,"created_at"=>"09/05/2023 16:51:00","updated_at"=>null,"deleted_at"=>null,"license_name"=>null,"license_email"=>null,"depreciate"=>null,"supplier_id"=>null,"expiration_date"=>null,"purchase_order"=>null,"termination_date"=>null,"maintained"=>"0","reassignable"=>"1","company_id"=>"10","manufacturer_id"=>null,"category_id"=>"16","mulaiberlaku"=>null],
            ["id"=>"7","name"=>"Prestasi Online","serial"=>null,"purchase_date"=>null,"purchase_cost"=>null,"order_number"=>null,"seats"=>"1","notes"=>"Aplikasi untuk meng-input nilai prestasi pegawai Pusat","user_id"=>null,"depreciation_id"=>null,"created_at"=>"09/06/2023 16:51:00","updated_at"=>null,"deleted_at"=>null,"license_name"=>null,"license_email"=>null,"depreciate"=>null,"supplier_id"=>null,"expiration_date"=>null,"purchase_order"=>null,"termination_date"=>null,"maintained"=>"0","reassignable"=>"1","company_id"=>"10","manufacturer_id"=>null,"category_id"=>"16","mulaiberlaku"=>null],
            ["id"=>"8","name"=>"TK Online","serial"=>null,"purchase_date"=>null,"purchase_cost"=>null,"order_number"=>null,"seats"=>"1","notes"=>"Mengelola data dan penghitungan tunjangan kinerja pegawai BPS","user_id"=>null,"depreciation_id"=>null,"created_at"=>"09/07/2023 16:51:00","updated_at"=>null,"deleted_at"=>null,"license_name"=>null,"license_email"=>null,"depreciate"=>null,"supplier_id"=>null,"expiration_date"=>null,"purchase_order"=>null,"termination_date"=>null,"maintained"=>"0","reassignable"=>"1","company_id"=>"10","manufacturer_id"=>null,"category_id"=>"16","mulaiberlaku"=>null],
            ["id"=>"9","name"=>"Sim Perundang-undangan","serial"=>null,"purchase_date"=>null,"purchase_cost"=>null,"order_number"=>null,"seats"=>"1","notes"=>"Kelola data perundang-undangan","user_id"=>null,"depreciation_id"=>null,"created_at"=>"09/08/2023 16:51:00","updated_at"=>null,"deleted_at"=>null,"license_name"=>null,"license_email"=>null,"depreciate"=>null,"supplier_id"=>null,"expiration_date"=>null,"purchase_order"=>null,"termination_date"=>null,"maintained"=>"0","reassignable"=>"1","company_id"=>"10","manufacturer_id"=>null,"category_id"=>"16","mulaiberlaku"=>null],
            ["id"=>"10","name"=>"SKP Online (Kinerja Pegawa)","serial"=>null,"purchase_date"=>null,"purchase_cost"=>null,"order_number"=>null,"seats"=>"1","notes"=>"Mendokumentasikan kegiatan pegawai melalui SKP dan CKP","user_id"=>null,"depreciation_id"=>null,"created_at"=>"09/09/2023 16:51:00","updated_at"=>null,"deleted_at"=>null,"license_name"=>null,"license_email"=>null,"depreciate"=>null,"supplier_id"=>null,"expiration_date"=>null,"purchase_order"=>null,"termination_date"=>null,"maintained"=>"0","reassignable"=>"1","company_id"=>"10","manufacturer_id"=>null,"category_id"=>"16","mulaiberlaku"=>null],
            ["id"=>"11","name"=>"PPID","serial"=>null,"purchase_date"=>null,"purchase_cost"=>null,"order_number"=>null,"seats"=>"1","notes"=>"Kelola buku tamu dan undangan","user_id"=>null,"depreciation_id"=>null,"created_at"=>"09/10/2023 16:51:00","updated_at"=>null,"deleted_at"=>null,"license_name"=>null,"license_email"=>null,"depreciate"=>null,"supplier_id"=>null,"expiration_date"=>null,"purchase_order"=>null,"termination_date"=>null,"maintained"=>"0","reassignable"=>"1","company_id"=>"10","manufacturer_id"=>null,"category_id"=>"16","mulaiberlaku"=>null],
            ["id"=>"12","name"=>"Sijafung","serial"=>null,"purchase_date"=>null,"purchase_cost"=>null,"order_number"=>null,"seats"=>"1","notes"=>"Kelola data pejabat fungsional dan DUPAK","user_id"=>null,"depreciation_id"=>null,"created_at"=>"09/11/2023 16:51:00","updated_at"=>null,"deleted_at"=>null,"license_name"=>null,"license_email"=>null,"depreciate"=>null,"supplier_id"=>null,"expiration_date"=>null,"purchase_order"=>null,"termination_date"=>null,"maintained"=>"0","reassignable"=>"1","company_id"=>"10","manufacturer_id"=>null,"category_id"=>"16","mulaiberlaku"=>null],
            ["id"=>"13","name"=>"Katalog Datamikro","serial"=>null,"purchase_date"=>null,"purchase_cost"=>null,"order_number"=>null,"seats"=>"1","notes"=>"Kumpulan data mikro dan metadata di Badan Pusat Statistik dari hasil sensus, survei, maupun kompilasi","user_id"=>null,"depreciation_id"=>null,"created_at"=>"09/12/2023 16:51:00","updated_at"=>null,"deleted_at"=>null,"license_name"=>null,"license_email"=>null,"depreciate"=>null,"supplier_id"=>null,"expiration_date"=>null,"purchase_order"=>null,"termination_date"=>null,"maintained"=>"0","reassignable"=>"1","company_id"=>"10","manufacturer_id"=>null,"category_id"=>"16","mulaiberlaku"=>null],
            ["id"=>"14","name"=>"Sistem Manajemen Data dan Metadata","serial"=>null,"purchase_date"=>null,"purchase_cost"=>null,"order_number"=>null,"seats"=>"1","notes"=>"Informasi Data dan Kelengkapannya yang disimpan di PTI","user_id"=>null,"depreciation_id"=>null,"created_at"=>"09/13/2023 16:51:00","updated_at"=>null,"deleted_at"=>null,"license_name"=>null,"license_email"=>null,"depreciate"=>null,"supplier_id"=>null,"expiration_date"=>null,"purchase_order"=>null,"termination_date"=>null,"maintained"=>"0","reassignable"=>"1","company_id"=>"10","manufacturer_id"=>null,"category_id"=>"16","mulaiberlaku"=>null],
            ["id"=>"15","name"=>"Sistem Pengelolaan Teknologi Informasi (Simpati)","serial"=>null,"purchase_date"=>null,"purchase_cost"=>null,"order_number"=>null,"seats"=>"1","notes"=>"Untuk pengelolaan data perangkat TI non jaringan","user_id"=>null,"depreciation_id"=>null,"created_at"=>"09/14/2023 16:51:00","updated_at"=>null,"deleted_at"=>null,"license_name"=>null,"license_email"=>null,"depreciate"=>null,"supplier_id"=>null,"expiration_date"=>null,"purchase_order"=>null,"termination_date"=>null,"maintained"=>"0","reassignable"=>"1","company_id"=>"10","manufacturer_id"=>null,"category_id"=>"16","mulaiberlaku"=>null],
            ["id"=>"16","name"=>"Sistem Laporan Pekerjaan Pimpinan (Eselon I & II )","serial"=>null,"purchase_date"=>null,"purchase_cost"=>null,"order_number"=>null,"seats"=>"1","notes"=>"Pelaporan kegiatan yang dilakukan oleh eselon 1 dan 2 dan hasilnya","user_id"=>null,"depreciation_id"=>null,"created_at"=>"09/15/2023 16:51:00","updated_at"=>null,"deleted_at"=>null,"license_name"=>null,"license_email"=>null,"depreciate"=>null,"supplier_id"=>null,"expiration_date"=>null,"purchase_order"=>null,"termination_date"=>null,"maintained"=>"0","reassignable"=>"1","company_id"=>"10","manufacturer_id"=>null,"category_id"=>"16","mulaiberlaku"=>null],
            ["id"=>"17","name"=>"Aplikasi Progres Mutasi Pegawai","serial"=>null,"purchase_date"=>null,"purchase_cost"=>null,"order_number"=>null,"seats"=>"1","notes"=>"Aplikasi untuk memantau progres kenaikan pangkat, pencantuman gelar,pengajuan pindah, pengajuan pensiun, peninjauan masa kerja.","user_id"=>null,"depreciation_id"=>null,"created_at"=>"09/16/2023 16:51:00","updated_at"=>null,"deleted_at"=>null,"license_name"=>null,"license_email"=>null,"depreciate"=>null,"supplier_id"=>null,"expiration_date"=>null,"purchase_order"=>null,"termination_date"=>null,"maintained"=>"0","reassignable"=>"1","company_id"=>"10","manufacturer_id"=>null,"category_id"=>"16","mulaiberlaku"=>null],
            ["id"=>"18","name"=>"Aplikasi Uji Kompetensi Jabatan Fungsional Statistisi dan Pranata Komputer","serial"=>null,"purchase_date"=>null,"purchase_cost"=>null,"order_number"=>null,"seats"=>"1","notes"=>"Untuk penyelenggaraan ujian kompetensi statistisi dan pranata komputer","user_id"=>null,"depreciation_id"=>null,"created_at"=>"09/17/2023 16:51:00","updated_at"=>null,"deleted_at"=>null,"license_name"=>null,"license_email"=>null,"depreciate"=>null,"supplier_id"=>null,"expiration_date"=>null,"purchase_order"=>null,"termination_date"=>null,"maintained"=>"0","reassignable"=>"1","company_id"=>"10","manufacturer_id"=>null,"category_id"=>"16","mulaiberlaku"=>null],
            ["id"=>"19","name"=>"Web Humas (sihumas)","serial"=>null,"purchase_date"=>null,"purchase_cost"=>null,"order_number"=>null,"seats"=>"1","notes"=>"Untuk menginformasikan berita terkini/kegiatan BPS kepada masyarakat","user_id"=>null,"depreciation_id"=>null,"created_at"=>"09/18/2023 16:51:00","updated_at"=>null,"deleted_at"=>null,"license_name"=>null,"license_email"=>null,"depreciate"=>null,"supplier_id"=>null,"expiration_date"=>null,"purchase_order"=>null,"termination_date"=>null,"maintained"=>"0","reassignable"=>"1","company_id"=>"10","manufacturer_id"=>null,"category_id"=>"16","mulaiberlaku"=>null],
            ["id"=>"20","name"=>"Web RB","serial"=>null,"purchase_date"=>null,"purchase_cost"=>null,"order_number"=>null,"seats"=>"1","notes"=>"Untuk menginformasikan berita terkini/kegiatan mengenai reformasi birokrasi yang ada di BPS","user_id"=>null,"depreciation_id"=>null,"created_at"=>"09/19/2023 16:51:00","updated_at"=>null,"deleted_at"=>null,"license_name"=>null,"license_email"=>null,"depreciate"=>null,"supplier_id"=>null,"expiration_date"=>null,"purchase_order"=>null,"termination_date"=>null,"maintained"=>"0","reassignable"=>"1","company_id"=>"10","manufacturer_id"=>null,"category_id"=>"16","mulaiberlaku"=>null],
            ["id"=>"21","name"=>"Aplikasi 360","serial"=>null,"purchase_date"=>null,"purchase_cost"=>null,"order_number"=>null,"seats"=>"1","notes"=>"Penilaian Performa Pegawai Secara 360 Derajat","user_id"=>null,"depreciation_id"=>null,"created_at"=>"09/20/2023 16:51:00","updated_at"=>null,"deleted_at"=>null,"license_name"=>null,"license_email"=>null,"depreciate"=>null,"supplier_id"=>null,"expiration_date"=>null,"purchase_order"=>null,"termination_date"=>null,"maintained"=>"0","reassignable"=>"1","company_id"=>"10","manufacturer_id"=>null,"category_id"=>"16","mulaiberlaku"=>null],
            ["id"=>"22","name"=>"Aplikasi CAPI (ICS/FASIH)","serial"=>null,"purchase_date"=>null,"purchase_cost"=>null,"order_number"=>null,"seats"=>"1","notes"=>"Aplikasi untuk proses data entri kuesioner dan/atau tarik sampel berbasis CAPI (ICS/FASIH) sensus/survei : 1. Aplikasi Podes 2018; 2. Dashboard Podes 2018; 3. LFSP2020 - C2","user_id"=>null,"depreciation_id"=>null,"created_at"=>"09/21/2023 16:51:00","updated_at"=>null,"deleted_at"=>null,"license_name"=>null,"license_email"=>null,"depreciate"=>null,"supplier_id"=>null,"expiration_date"=>null,"purchase_order"=>null,"termination_date"=>null,"maintained"=>"0","reassignable"=>"1","company_id"=>"10","manufacturer_id"=>null,"category_id"=>"16","mulaiberlaku"=>null],
            ["id"=>"23","name"=>"Integrated Collection System","serial"=>null,"purchase_date"=>null,"purchase_cost"=>null,"order_number"=>null,"seats"=>"1","notes"=>"� Manajemen Survei\n� Manajemen Petugas (Assignment)\n� Monitoring\n� Desain Kuesioner\n� Pencacahan dengan CAPI\n� CAWI","user_id"=>null,"depreciation_id"=>null,"created_at"=>"09/22/2023 16:51:00","updated_at"=>null,"deleted_at"=>null,"license_name"=>null,"license_email"=>null,"depreciate"=>null,"supplier_id"=>null,"expiration_date"=>null,"purchase_order"=>null,"termination_date"=>null,"maintained"=>"0","reassignable"=>"1","company_id"=>"10","manufacturer_id"=>null,"category_id"=>"16","mulaiberlaku"=>null],
            ["id"=>"24","name"=>"Halo Sis (halosis.bps.go.id)","serial"=>null,"purchase_date"=>null,"purchase_cost"=>null,"order_number"=>null,"seats"=>"1","notes"=>"� Mengelola permintaan layanan TI\n� Mengelola penyediaan layanan TI oleh Dir. SIS\n� Menyediakan knowledge base terkait layanan TI","user_id"=>null,"depreciation_id"=>null,"created_at"=>"09/23/2023 16:51:00","updated_at"=>null,"deleted_at"=>null,"license_name"=>null,"license_email"=>null,"depreciate"=>null,"supplier_id"=>null,"expiration_date"=>null,"purchase_order"=>null,"termination_date"=>null,"maintained"=>"0","reassignable"=>"1","company_id"=>"10","manufacturer_id"=>null,"category_id"=>"16","mulaiberlaku"=>null],
            ["id"=>"25","name"=>"SIPA","serial"=>null,"purchase_date"=>null,"purchase_cost"=>null,"order_number"=>null,"seats"=>"1","notes"=>"� Mengelola permintaan layanan TI khusus terkait pembuatan aplikasi\n� Alokasi permintaan terhadap programmer","user_id"=>null,"depreciation_id"=>null,"created_at"=>"09/24/2023 16:51:00","updated_at"=>null,"deleted_at"=>null,"license_name"=>null,"license_email"=>null,"depreciate"=>null,"supplier_id"=>null,"expiration_date"=>null,"purchase_order"=>null,"termination_date"=>null,"maintained"=>"0","reassignable"=>"1","company_id"=>"10","manufacturer_id"=>null,"category_id"=>"16","mulaiberlaku"=>null],
            ["id"=>"26","name"=>"Dashboard SP2020","serial"=>null,"purchase_date"=>null,"purchase_cost"=>null,"order_number"=>null,"seats"=>"1","notes"=>"� Monitoring pengumpulan data SP 2020","user_id"=>null,"depreciation_id"=>null,"created_at"=>"09/25/2023 16:51:00","updated_at"=>null,"deleted_at"=>null,"license_name"=>null,"license_email"=>null,"depreciate"=>null,"supplier_id"=>null,"expiration_date"=>null,"purchase_order"=>null,"termination_date"=>null,"maintained"=>"0","reassignable"=>"1","company_id"=>"10","manufacturer_id"=>null,"category_id"=>"16","mulaiberlaku"=>null],
            ["id"=>"27","name"=>"Website statcap cerdas","serial"=>null,"purchase_date"=>null,"purchase_cost"=>null,"order_number"=>null,"seats"=>"1","notes"=>"� Menampilkan informasi mengenai program Statcap Cerdas BPS","user_id"=>null,"depreciation_id"=>null,"created_at"=>"09/26/2023 16:51:00","updated_at"=>null,"deleted_at"=>null,"license_name"=>null,"license_email"=>null,"depreciate"=>null,"supplier_id"=>null,"expiration_date"=>null,"purchase_order"=>null,"termination_date"=>null,"maintained"=>"0","reassignable"=>"1","company_id"=>"10","manufacturer_id"=>null,"category_id"=>"16","mulaiberlaku"=>null],
            ["id"=>"28","name"=>"Portal Statcap (Ms. Sharepoint)","serial"=>null,"purchase_date"=>null,"purchase_cost"=>null,"order_number"=>null,"seats"=>"1","notes"=>"� Mengelola kegiatan terkait Program Statcap\n� Platform kolaborasi antara Satker yang terlibat dalam Statcap\n� Repositori dokumen terkait statcap","user_id"=>null,"depreciation_id"=>null,"created_at"=>"09/27/2023 16:51:00","updated_at"=>null,"deleted_at"=>null,"license_name"=>null,"license_email"=>null,"depreciate"=>null,"supplier_id"=>null,"expiration_date"=>null,"purchase_order"=>null,"termination_date"=>null,"maintained"=>"0","reassignable"=>"1","company_id"=>"10","manufacturer_id"=>null,"category_id"=>"16","mulaiberlaku"=>null],
            ["id"=>"29","name"=>"Community","serial"=>null,"purchase_date"=>null,"purchase_cost"=>null,"order_number"=>null,"seats"=>"1","notes"=>"Portal dan Forum Komunitas BPS (community.bps.go.id)","user_id"=>null,"depreciation_id"=>null,"created_at"=>"09/28/2023 16:51:00","updated_at"=>null,"deleted_at"=>null,"license_name"=>null,"license_email"=>null,"depreciate"=>null,"supplier_id"=>null,"expiration_date"=>null,"purchase_order"=>null,"termination_date"=>null,"maintained"=>"0","reassignable"=>"1","company_id"=>"10","manufacturer_id"=>null,"category_id"=>"16","mulaiberlaku"=>null],
            ["id"=>"30","name"=>"Woowtime 6.5","serial"=>null,"purchase_date"=>null,"purchase_cost"=>null,"order_number"=>null,"seats"=>"1","notes"=>"Presensi Online BPS Kab/Kota","user_id"=>null,"depreciation_id"=>null,"created_at"=>"09/29/2023 16:51:00","updated_at"=>null,"deleted_at"=>null,"license_name"=>null,"license_email"=>null,"depreciate"=>null,"supplier_id"=>null,"expiration_date"=>null,"purchase_order"=>null,"termination_date"=>null,"maintained"=>"0","reassignable"=>"1","company_id"=>"10","manufacturer_id"=>null,"category_id"=>"16","mulaiberlaku"=>null],
            ["id"=>"31","name"=>"Woowtime 5.2","serial"=>null,"purchase_date"=>null,"purchase_cost"=>null,"order_number"=>null,"seats"=>"1","notes"=>"Presensi Online BPS Provinsi","user_id"=>null,"depreciation_id"=>null,"created_at"=>"09/30/2023 16:51:00","updated_at"=>null,"deleted_at"=>null,"license_name"=>null,"license_email"=>null,"depreciate"=>null,"supplier_id"=>null,"expiration_date"=>null,"purchase_order"=>null,"termination_date"=>null,"maintained"=>"0","reassignable"=>"1","company_id"=>"10","manufacturer_id"=>null,"category_id"=>"16","mulaiberlaku"=>null],
            ["id"=>"32","name"=>"Laporanwfh","serial"=>null,"purchase_date"=>null,"purchase_cost"=>null,"order_number"=>null,"seats"=>"1","notes"=>"Sistem yang digunakan untuk mengupload laporan Work from home (WFH) laporanwfh.bps.go.id","user_id"=>null,"depreciation_id"=>null,"created_at"=>"10/01/2023 16:51:00","updated_at"=>null,"deleted_at"=>null,"license_name"=>null,"license_email"=>null,"depreciate"=>null,"supplier_id"=>null,"expiration_date"=>null,"purchase_order"=>null,"termination_date"=>null,"maintained"=>"0","reassignable"=>"1","company_id"=>"10","manufacturer_id"=>null,"category_id"=>"16","mulaiberlaku"=>null],
            ["id"=>"33","name"=>"Rekrutmen BPS","serial"=>null,"purchase_date"=>null,"purchase_cost"=>null,"order_number"=>null,"seats"=>"1","notes"=>"Website rekrutmen jabatan rekrutmen.bps.go.id/","user_id"=>null,"depreciation_id"=>null,"created_at"=>"10/02/2023 16:51:00","updated_at"=>null,"deleted_at"=>null,"license_name"=>null,"license_email"=>null,"depreciate"=>null,"supplier_id"=>null,"expiration_date"=>null,"purchase_order"=>null,"termination_date"=>null,"maintained"=>"0","reassignable"=>"1","company_id"=>"10","manufacturer_id"=>null,"category_id"=>"16","mulaiberlaku"=>null],
            ["id"=>"34","name"=>"Email","serial"=>null,"purchase_date"=>null,"purchase_cost"=>null,"order_number"=>null,"seats"=>"1","notes"=>"Sarana komunikasi antar pegawai BPS dan instansi di luar BPS. (mail.bps.go.id)","user_id"=>null,"depreciation_id"=>null,"created_at"=>"10/03/2023 16:51:00","updated_at"=>null,"deleted_at"=>null,"license_name"=>null,"license_email"=>null,"depreciate"=>null,"supplier_id"=>null,"expiration_date"=>null,"purchase_order"=>null,"termination_date"=>null,"maintained"=>"0","reassignable"=>"1","company_id"=>"10","manufacturer_id"=>null,"category_id"=>"16","mulaiberlaku"=>null],
            ["id"=>"35","name"=>"Arsip Email","serial"=>null,"purchase_date"=>null,"purchase_cost"=>null,"order_number"=>null,"seats"=>"1","notes"=>"Arsip atau backup email lama pegawai BPS sebelum migrasi ke mail.bps.go.id. (arsipmail.bps.go.id)","user_id"=>null,"depreciation_id"=>null,"created_at"=>"10/04/2023 16:51:00","updated_at"=>null,"deleted_at"=>null,"license_name"=>null,"license_email"=>null,"depreciate"=>null,"supplier_id"=>null,"expiration_date"=>null,"purchase_order"=>null,"termination_date"=>null,"maintained"=>"0","reassignable"=>"1","company_id"=>"10","manufacturer_id"=>null,"category_id"=>"16","mulaiberlaku"=>null],
            ["id"=>"36","name"=>"Aset DC","serial"=>null,"purchase_date"=>null,"purchase_cost"=>null,"order_number"=>null,"seats"=>"1","notes"=>"Sistem Manajemen Aset Data Center BPS: agon.bps.go.id","user_id"=>null,"depreciation_id"=>null,"created_at"=>"10/05/2023 16:51:00","updated_at"=>null,"deleted_at"=>null,"license_name"=>null,"license_email"=>null,"depreciate"=>null,"supplier_id"=>null,"expiration_date"=>null,"purchase_order"=>null,"termination_date"=>null,"maintained"=>"0","reassignable"=>"1","company_id"=>"10","manufacturer_id"=>null,"category_id"=>"16","mulaiberlaku"=>null],
            ["id"=>"37","name"=>"meetapp","serial"=>null,"purchase_date"=>null,"purchase_cost"=>null,"order_number"=>null,"seats"=>"1","notes"=>"Sistem Manajemen Rapat, mulai dari membuat undangan, membuat notulensi, permintaan zoom meeting (meetapp.bps.go.id)","user_id"=>null,"depreciation_id"=>null,"created_at"=>"10/06/2023 16:51:00","updated_at"=>null,"deleted_at"=>null,"license_name"=>null,"license_email"=>null,"depreciate"=>null,"supplier_id"=>null,"expiration_date"=>null,"purchase_order"=>null,"termination_date"=>null,"maintained"=>"0","reassignable"=>"1","company_id"=>"10","manufacturer_id"=>null,"category_id"=>"16","mulaiberlaku"=>null],
            ["id"=>"38","name"=>"Kolaborasi","serial"=>null,"purchase_date"=>null,"purchase_cost"=>null,"order_number"=>null,"seats"=>"1","notes"=>"Portal Kolaborasi pegawai BPS: kolaborasi.bps.go.id","user_id"=>null,"depreciation_id"=>null,"created_at"=>"10/07/2023 16:51:00","updated_at"=>null,"deleted_at"=>null,"license_name"=>null,"license_email"=>null,"depreciate"=>null,"supplier_id"=>null,"expiration_date"=>null,"purchase_order"=>null,"termination_date"=>null,"maintained"=>"0","reassignable"=>"1","company_id"=>"10","manufacturer_id"=>null,"category_id"=>"16","mulaiberlaku"=>null],
            ["id"=>"39","name"=>"KSA","serial"=>null,"purchase_date"=>null,"purchase_cost"=>null,"order_number"=>null,"seats"=>"1","notes"=>"Sistem pengumpulan data tanaman pangan (padi) berbasis kerangka sampel area (KSA). (ksa.bps.go.id)","user_id"=>null,"depreciation_id"=>null,"created_at"=>"10/08/2023 16:51:00","updated_at"=>null,"deleted_at"=>null,"license_name"=>null,"license_email"=>null,"depreciate"=>null,"supplier_id"=>null,"expiration_date"=>null,"purchase_order"=>null,"termination_date"=>null,"maintained"=>"0","reassignable"=>"1","company_id"=>"10","manufacturer_id"=>null,"category_id"=>"16","mulaiberlaku"=>null],
            ["id"=>"40","name"=>"Sistem penjadwalan video conference","serial"=>null,"purchase_date"=>null,"purchase_cost"=>null,"order_number"=>null,"seats"=>"1","notes"=>"Sistem penjadwalan video conference BPS: noc.bps.go.id/vicon","user_id"=>null,"depreciation_id"=>null,"created_at"=>"10/09/2023 16:51:00","updated_at"=>null,"deleted_at"=>null,"license_name"=>null,"license_email"=>null,"depreciate"=>null,"supplier_id"=>null,"expiration_date"=>null,"purchase_order"=>null,"termination_date"=>null,"maintained"=>"0","reassignable"=>"1","company_id"=>"10","manufacturer_id"=>null,"category_id"=>"16","mulaiberlaku"=>null],
            ["id"=>"41","name"=>"SPK Online","serial"=>null,"purchase_date"=>null,"purchase_cost"=>null,"order_number"=>null,"seats"=>"1","notes"=>"Pencarian kode klasifikasi: spkonline.bps.go.id/spkonline","user_id"=>null,"depreciation_id"=>null,"created_at"=>"10/10/2023 16:51:00","updated_at"=>null,"deleted_at"=>null,"license_name"=>null,"license_email"=>null,"depreciate"=>null,"supplier_id"=>null,"expiration_date"=>null,"purchase_order"=>null,"termination_date"=>null,"maintained"=>"0","reassignable"=>"1","company_id"=>"9","manufacturer_id"=>null,"category_id"=>"16","mulaiberlaku"=>null],
            ["id"=>"42","name"=>"Filelib","serial"=>null,"purchase_date"=>null,"purchase_cost"=>null,"order_number"=>null,"seats"=>"1","notes"=>"Pertukaran file antar pusat prov dan kota/kab: filelib.bps.go.id/","user_id"=>null,"depreciation_id"=>null,"created_at"=>"10/11/2023 16:51:00","updated_at"=>null,"deleted_at"=>null,"license_name"=>null,"license_email"=>null,"depreciate"=>null,"supplier_id"=>null,"expiration_date"=>null,"purchase_order"=>null,"termination_date"=>null,"maintained"=>"0","reassignable"=>"1","company_id"=>"10","manufacturer_id"=>null,"category_id"=>"16","mulaiberlaku"=>null],
            ["id"=>"43","name"=>"Laci","serial"=>null,"purchase_date"=>null,"purchase_cost"=>null,"order_number"=>null,"seats"=>"1","notes"=>"Sama seperti dropbox: laci.bps.go.id/","user_id"=>null,"depreciation_id"=>null,"created_at"=>"10/12/2023 16:51:00","updated_at"=>null,"deleted_at"=>null,"license_name"=>null,"license_email"=>null,"depreciate"=>null,"supplier_id"=>null,"expiration_date"=>null,"purchase_order"=>null,"termination_date"=>null,"maintained"=>"0","reassignable"=>"1","company_id"=>"10","manufacturer_id"=>null,"category_id"=>"16","mulaiberlaku"=>null],
            ["id"=>"44","name"=>"Web hosting bps provinsi dan kotakab (549 web)","serial"=>null,"purchase_date"=>null,"purchase_cost"=>null,"order_number"=>null,"seats"=>"1","notes"=>"Manajemen web untuk bps selindo","user_id"=>null,"depreciation_id"=>null,"created_at"=>"10/13/2023 16:51:00","updated_at"=>null,"deleted_at"=>null,"license_name"=>null,"license_email"=>null,"depreciate"=>null,"supplier_id"=>null,"expiration_date"=>null,"purchase_order"=>null,"termination_date"=>null,"maintained"=>"0","reassignable"=>"1","company_id"=>"10","manufacturer_id"=>null,"category_id"=>"16","mulaiberlaku"=>null],
            ["id"=>"45","name"=>"Portal Publikasi","serial"=>null,"purchase_date"=>null,"purchase_cost"=>null,"order_number"=>null,"seats"=>"1","notes"=>"Manajemen publikasi untuk bps pusat dan selindo. (portalpublikasi.bps.go.id/)","user_id"=>null,"depreciation_id"=>null,"created_at"=>"10/14/2023 16:51:00","updated_at"=>null,"deleted_at"=>null,"license_name"=>null,"license_email"=>null,"depreciate"=>null,"supplier_id"=>null,"expiration_date"=>null,"purchase_order"=>null,"termination_date"=>null,"maintained"=>"0","reassignable"=>"1","company_id"=>"9","manufacturer_id"=>null,"category_id"=>"16","mulaiberlaku"=>null],
            ["id"=>"46","name"=>"SIMBRS","serial"=>null,"purchase_date"=>null,"purchase_cost"=>null,"order_number"=>null,"seats"=>"1","notes"=>"Penyusunan BRS simbrs.bps.go.id","user_id"=>null,"depreciation_id"=>null,"created_at"=>"10/15/2023 16:51:00","updated_at"=>null,"deleted_at"=>null,"license_name"=>null,"license_email"=>null,"depreciate"=>null,"supplier_id"=>null,"expiration_date"=>null,"purchase_order"=>null,"termination_date"=>null,"maintained"=>"0","reassignable"=>"1","company_id"=>"9","manufacturer_id"=>null,"category_id"=>"16","mulaiberlaku"=>null],
            ["id"=>"47","name"=>"SIMDASI","serial"=>null,"purchase_date"=>null,"purchase_cost"=>null,"order_number"=>null,"seats"=>"1","notes"=>"Manajemen data SI-DDA simdasi.bps.go.id","user_id"=>null,"depreciation_id"=>null,"created_at"=>"10/16/2023 16:51:00","updated_at"=>null,"deleted_at"=>null,"license_name"=>null,"license_email"=>null,"depreciate"=>null,"supplier_id"=>null,"expiration_date"=>null,"purchase_order"=>null,"termination_date"=>null,"maintained"=>"0","reassignable"=>"1","company_id"=>"9","manufacturer_id"=>null,"category_id"=>"16","mulaiberlaku"=>null],
            ["id"=>"48","name"=>"Sistem Repository Gambar dan Infografis","serial"=>null,"purchase_date"=>null,"purchase_cost"=>null,"order_number"=>null,"seats"=>"1","notes"=>"Repository Gambar publikasi.bps.go.id/repositorygambar/index.php dan Infografis publikasi.bps.go.id/infografis/index.php","user_id"=>null,"depreciation_id"=>null,"created_at"=>"10/17/2023 16:51:00","updated_at"=>null,"deleted_at"=>null,"license_name"=>null,"license_email"=>null,"depreciate"=>null,"supplier_id"=>null,"expiration_date"=>null,"purchase_order"=>null,"termination_date"=>null,"maintained"=>"0","reassignable"=>"1","company_id"=>"9","manufacturer_id"=>null,"category_id"=>"16","mulaiberlaku"=>null],
            ["id"=>"49","name"=>"Simotik","serial"=>null,"purchase_date"=>null,"purchase_cost"=>null,"order_number"=>null,"seats"=>"1","notes"=>"Manejemen publikasi untuk bps pusat publikasi.bps.go.id/simotik","user_id"=>null,"depreciation_id"=>null,"created_at"=>"10/18/2023 16:51:00","updated_at"=>null,"deleted_at"=>null,"license_name"=>null,"license_email"=>null,"depreciate"=>null,"supplier_id"=>null,"expiration_date"=>null,"purchase_order"=>null,"termination_date"=>null,"maintained"=>"0","reassignable"=>"1","company_id"=>"9","manufacturer_id"=>null,"category_id"=>"16","mulaiberlaku"=>null],
            ["id"=>"50","name"=>"WebApi","serial"=>null,"purchase_date"=>null,"purchase_cost"=>null,"order_number"=>null,"seats"=>"1","notes"=>"Penyedia data di web untuk publik: webapi.bps.go.id/","user_id"=>null,"depreciation_id"=>null,"created_at"=>"10/19/2023 16:51:00","updated_at"=>null,"deleted_at"=>null,"license_name"=>null,"license_email"=>null,"depreciate"=>null,"supplier_id"=>null,"expiration_date"=>null,"purchase_order"=>null,"termination_date"=>null,"maintained"=>"0","reassignable"=>"1","company_id"=>null,"manufacturer_id"=>null,"category_id"=>"16","mulaiberlaku"=>null],
            ["id"=>"51","name"=>"Git Server","serial"=>null,"purchase_date"=>null,"purchase_cost"=>null,"order_number"=>null,"seats"=>"1","notes"=>"Manajemen versi untuk sumber kode aplikasi: git.bps.go.id/","user_id"=>null,"depreciation_id"=>null,"created_at"=>"10/20/2023 16:51:00","updated_at"=>null,"deleted_at"=>null,"license_name"=>null,"license_email"=>null,"depreciate"=>null,"supplier_id"=>null,"expiration_date"=>null,"purchase_order"=>null,"termination_date"=>null,"maintained"=>"0","reassignable"=>"1","company_id"=>"10","manufacturer_id"=>null,"category_id"=>"16","mulaiberlaku"=>null],
            ["id"=>"52","name"=>"DNS publik","serial"=>null,"purchase_date"=>null,"purchase_cost"=>null,"order_number"=>null,"seats"=>"1","notes"=>"Manajemen penerjemah dari ip ke nama domain","user_id"=>null,"depreciation_id"=>null,"created_at"=>"10/21/2023 16:51:00","updated_at"=>null,"deleted_at"=>null,"license_name"=>null,"license_email"=>null,"depreciate"=>null,"supplier_id"=>null,"expiration_date"=>null,"purchase_order"=>null,"termination_date"=>null,"maintained"=>"0","reassignable"=>"1","company_id"=>"10","manufacturer_id"=>null,"category_id"=>"16","mulaiberlaku"=>null],
            ["id"=>"53","name"=>"Ammon Simkeu","serial"=>null,"purchase_date"=>null,"purchase_cost"=>null,"order_number"=>null,"seats"=>"1","notes"=>"Manajemen keuangan dengan samba sharing","user_id"=>null,"depreciation_id"=>null,"created_at"=>"10/22/2023 16:51:00","updated_at"=>null,"deleted_at"=>null,"license_name"=>null,"license_email"=>null,"depreciate"=>null,"supplier_id"=>null,"expiration_date"=>null,"purchase_order"=>null,"termination_date"=>null,"maintained"=>"0","reassignable"=>"1","company_id"=>"10","manufacturer_id"=>null,"category_id"=>"16","mulaiberlaku"=>null],
            ["id"=>"54","name"=>"Spoolserver Publikasi","serial"=>null,"purchase_date"=>null,"purchase_cost"=>null,"order_number"=>null,"seats"=>"1","notes"=>"Repositori data untuk subdit PKS","user_id"=>null,"depreciation_id"=>null,"created_at"=>"10/23/2023 16:51:00","updated_at"=>null,"deleted_at"=>null,"license_name"=>null,"license_email"=>null,"depreciate"=>null,"supplier_id"=>null,"expiration_date"=>null,"purchase_order"=>null,"termination_date"=>null,"maintained"=>"0","reassignable"=>"1","company_id"=>"9","manufacturer_id"=>null,"category_id"=>"16","mulaiberlaku"=>null],
            ["id"=>"55","name"=>"Ekspor impor","serial"=>null,"purchase_date"=>null,"purchase_cost"=>null,"order_number"=>null,"seats"=>"1","notes"=>"Database server rutin ekspor impor","user_id"=>null,"depreciation_id"=>null,"created_at"=>"10/24/2023 16:51:00","updated_at"=>null,"deleted_at"=>null,"license_name"=>null,"license_email"=>null,"depreciate"=>null,"supplier_id"=>null,"expiration_date"=>null,"purchase_order"=>null,"termination_date"=>null,"maintained"=>"0","reassignable"=>"1","company_id"=>"10","manufacturer_id"=>null,"category_id"=>"16","mulaiberlaku"=>null],
            ["id"=>"56","name"=>"BPS Smart Service","serial"=>null,"purchase_date"=>null,"purchase_cost"=>null,"order_number"=>null,"seats"=>"1","notes"=>"Virtualisasi Desktop (Virtual Desktop Infrastructure)","user_id"=>null,"depreciation_id"=>null,"created_at"=>"10/25/2023 16:51:00","updated_at"=>null,"deleted_at"=>null,"license_name"=>null,"license_email"=>null,"depreciate"=>null,"supplier_id"=>null,"expiration_date"=>null,"purchase_order"=>null,"termination_date"=>null,"maintained"=>"0","reassignable"=>"1","company_id"=>"10","manufacturer_id"=>null,"category_id"=>"16","mulaiberlaku"=>null],
            ["id"=>"57","name"=>"DNS Privat","serial"=>null,"purchase_date"=>null,"purchase_cost"=>null,"order_number"=>null,"seats"=>"1","notes"=>"Manajemen penerjeman dari ip ke nama domain untuk lingkungan privat","user_id"=>null,"depreciation_id"=>null,"created_at"=>"10/26/2023 16:51:00","updated_at"=>null,"deleted_at"=>null,"license_name"=>null,"license_email"=>null,"depreciate"=>null,"supplier_id"=>null,"expiration_date"=>null,"purchase_order"=>null,"termination_date"=>null,"maintained"=>"0","reassignable"=>"1","company_id"=>"10","manufacturer_id"=>null,"category_id"=>"16","mulaiberlaku"=>null],
            ["id"=>"58","name"=>"Recording dan Streaming VICON","serial"=>null,"purchase_date"=>null,"purchase_cost"=>null,"order_number"=>null,"seats"=>"1","notes"=>"Perekaman hasil pelaksanaan VICON dan streaming VICON yang sedang berlangsung","user_id"=>null,"depreciation_id"=>null,"created_at"=>"10/27/2023 16:51:00","updated_at"=>null,"deleted_at"=>null,"license_name"=>null,"license_email"=>null,"depreciate"=>null,"supplier_id"=>null,"expiration_date"=>null,"purchase_order"=>null,"termination_date"=>null,"maintained"=>"0","reassignable"=>"1","company_id"=>"10","manufacturer_id"=>null,"category_id"=>"16","mulaiberlaku"=>null],
            ["id"=>"59","name"=>"Perpesanan berbasis Text/Audio/Video","serial"=>null,"purchase_date"=>null,"purchase_cost"=>null,"order_number"=>null,"seats"=>"1","notes"=>"Untuk kebutuhan komunikasi dan kolaborasi","user_id"=>null,"depreciation_id"=>null,"created_at"=>"10/28/2023 16:51:00","updated_at"=>null,"deleted_at"=>null,"license_name"=>null,"license_email"=>null,"depreciate"=>null,"supplier_id"=>null,"expiration_date"=>null,"purchase_order"=>null,"termination_date"=>null,"maintained"=>"0","reassignable"=>"1","company_id"=>"10","manufacturer_id"=>null,"category_id"=>"16","mulaiberlaku"=>null],
            ["id"=>"60","name"=>"Aplikasi Uji Kompetensi","serial"=>null,"purchase_date"=>null,"purchase_cost"=>null,"order_number"=>null,"seats"=>"1","notes"=>"Aplikasi yang digunakan untuk uji kompetensi secara online. (ukom.bps.go.id)","user_id"=>null,"depreciation_id"=>null,"created_at"=>"10/29/2023 16:51:00","updated_at"=>null,"deleted_at"=>null,"license_name"=>null,"license_email"=>null,"depreciate"=>null,"supplier_id"=>null,"expiration_date"=>null,"purchase_order"=>null,"termination_date"=>null,"maintained"=>"0","reassignable"=>"1","company_id"=>"10","manufacturer_id"=>null,"category_id"=>"16","mulaiberlaku"=>null],
            ["id"=>"61","name"=>"API Community","serial"=>null,"purchase_date"=>null,"purchase_cost"=>null,"order_number"=>null,"seats"=>"1","notes"=>"Menyediakan API Community","user_id"=>null,"depreciation_id"=>null,"created_at"=>"10/30/2023 16:51:00","updated_at"=>null,"deleted_at"=>null,"license_name"=>null,"license_email"=>null,"depreciate"=>null,"supplier_id"=>null,"expiration_date"=>null,"purchase_order"=>null,"termination_date"=>null,"maintained"=>"0","reassignable"=>"1","company_id"=>"10","manufacturer_id"=>null,"category_id"=>"16","mulaiberlaku"=>null],
            ["id"=>"62","name"=>"Shorten Link","serial"=>null,"purchase_date"=>null,"purchase_cost"=>null,"order_number"=>null,"seats"=>"1","notes"=>"Layanan shorten link BPS: s.bps.go.id","user_id"=>null,"depreciation_id"=>null,"created_at"=>"10/31/2023 16:51:00","updated_at"=>null,"deleted_at"=>null,"license_name"=>null,"license_email"=>null,"depreciate"=>null,"supplier_id"=>null,"expiration_date"=>null,"purchase_order"=>null,"termination_date"=>null,"maintained"=>"0","reassignable"=>"1","company_id"=>"10","manufacturer_id"=>null,"category_id"=>"16","mulaiberlaku"=>null],
            ["id"=>"63","name"=>"LPSE","serial"=>null,"purchase_date"=>null,"purchase_cost"=>null,"order_number"=>null,"seats"=>"1","notes"=>"Website Layanan Pengadaan Secara Elektronik: lpse.bps.go.id","user_id"=>null,"depreciation_id"=>null,"created_at"=>"11/01/2023 16:51:00","updated_at"=>null,"deleted_at"=>null,"license_name"=>null,"license_email"=>null,"depreciate"=>null,"supplier_id"=>null,"expiration_date"=>null,"purchase_order"=>null,"termination_date"=>null,"maintained"=>"0","reassignable"=>"1","company_id"=>"10","manufacturer_id"=>null,"category_id"=>"16","mulaiberlaku"=>null],
            ["id"=>"64","name"=>"Dashboard","serial"=>null,"purchase_date"=>null,"purchase_cost"=>null,"order_number"=>null,"seats"=>"1","notes"=>"Monitoring pengumpulan data  Survei dan Sensus: dashboard.bps.go.id","user_id"=>null,"depreciation_id"=>null,"created_at"=>"11/02/2023 16:51:00","updated_at"=>null,"deleted_at"=>null,"license_name"=>null,"license_email"=>null,"depreciate"=>null,"supplier_id"=>null,"expiration_date"=>null,"purchase_order"=>null,"termination_date"=>null,"maintained"=>"0","reassignable"=>"1","company_id"=>"10","manufacturer_id"=>null,"category_id"=>"16","mulaiberlaku"=>null],
            ["id"=>"65","name"=>"KSA PRO","serial"=>null,"purchase_date"=>null,"purchase_cost"=>null,"order_number"=>null,"seats"=>"1","notes"=>"Sistem pengumpulan data tanaman pangan (padi) berbasis kerangka sampel area (KSA) yang terintegrasi mulai dari pengelolaan kerangka sampel, penggantian sampel, pendataan amatan di lapangan, pengawasan dan pemeriksaan, sampai tabulasi dan estimasi data. (ksapro-manajemen.bps.go.id)","user_id"=>null,"depreciation_id"=>null,"created_at"=>"11/03/2023 16:51:00","updated_at"=>null,"deleted_at"=>null,"license_name"=>null,"license_email"=>null,"depreciate"=>null,"supplier_id"=>null,"expiration_date"=>null,"purchase_order"=>null,"termination_date"=>null,"maintained"=>"0","reassignable"=>"1","company_id"=>"10","manufacturer_id"=>null,"category_id"=>"16","mulaiberlaku"=>null],
            ["id"=>"66","name"=>"Aplikasi Desktop Sensus/Survei","serial"=>null,"purchase_date"=>null,"purchase_cost"=>null,"order_number"=>null,"seats"=>"1","notes"=>"Aplikasi untuk proses data entri kuesioner dan/atau tarik sampel berbasis dekstop sensus/survei :\n1.��� Susenas \n2.��� Sakernas\n3.��� Updating Sakernas\n4.��� Pemutakhiran Longform SP2020\n5.��� Longform SP2020\n6.��� Pemutakhiran Ubinan\n7.��� Pola Distribusi (Poldis)\n8.��� SP2020 - C1 Data Entry\n9.��� SP2020 - C1 Data Capture\n10. Updating Susenas\n11.� Wisnus (VRTJ)\n12. Aplikasi Pengolahan Podes 2018\n13. Aplikasi Pengolahan SBH2018\n14. Aplikasi Pengolahan Sutas 2018\n15. SKLNP Tahunan","user_id"=>null,"depreciation_id"=>null,"created_at"=>"11/04/2023 16:51:00","updated_at"=>null,"deleted_at"=>null,"license_name"=>null,"license_email"=>null,"depreciate"=>null,"supplier_id"=>null,"expiration_date"=>null,"purchase_order"=>null,"termination_date"=>null,"maintained"=>"0","reassignable"=>"1","company_id"=>"10","manufacturer_id"=>null,"category_id"=>"16","mulaiberlaku"=>null]
        ];

        foreach (array_chunk($data,1000) as $t)  
        {
            DB::table('licenses')->insert($t); 
        }
    }
}
